/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clase;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author isidro
 */
public class VentanaHijosDeUnNodo extends javax.swing.JFrame {
    ArbolGeneral arbol = new ArbolGeneral();
    /**
     * Creates new form VentanaHijosDeUnNodo
     */
    public VentanaHijosDeUnNodo() {
        initComponents();
        GenerarArbol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNodo = new javax.swing.JLabel();
        txtPathNodo = new javax.swing.JTextField();
        btnBuscarHijos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaneMostrarHijos = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNodo.setText("Nodo a conocer sus hijos");

        btnBuscarHijos.setText("Buscar Hijos");
        btnBuscarHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHijosActionPerformed(evt);
            }
        });

        PaneMostrarHijos.setEditable(false);
        jScrollPane1.setViewportView(PaneMostrarHijos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblNodo)
                        .addGap(18, 18, 18)
                        .addComponent(txtPathNodo, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarHijos)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNodo)
                    .addComponent(txtPathNodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarHijos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHijosActionPerformed
        String pathBuscaHijos = txtPathNodo.getText();
        NodoGeneral NE = arbol.encontrarNodo(pathBuscaHijos);
        if(NE ==  null) showMessageDialog(this,"El nodo no fue encontrado");     
        String nodosHijos = NE.mostrarHijos();
        if(nodosHijos.isEmpty()) showMessageDialog(this,"El nodo padre no tiene hijos");
        PaneMostrarHijos.setText(nodosHijos);
    }//GEN-LAST:event_btnBuscarHijosActionPerformed

    
    public void GenerarArbol(){
        //Raiz
        arbol.insertar("/s/w", 's');
        //Hijos raiz /s
        arbol.insertar("/s", 'w');
        arbol.insertar("/s", 'j');
        arbol.insertar("/s", 'p');
        //Hijos /s/w
        arbol.insertar("/s/w", 'r');
        arbol.insertar("/s/w", '4');
        arbol.insertar("/s/w", 'h');
        arbol.insertar("/s/w", 'k');
        //Hijos /s/j
        arbol.insertar("/s/j", '9');
        arbol.insertar("/s/j", 'a');
        arbol.insertar("/s/j", 'b');
        //Hijos de /s/j/a
        arbol.insertar("/s/j/a", 'q');
        arbol.insertar("/s/j/a", 'w');
        arbol.insertar("/s/j/a", 'e');
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaHijosDeUnNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaHijosDeUnNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaHijosDeUnNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaHijosDeUnNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaHijosDeUnNodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane PaneMostrarHijos;
    private javax.swing.JButton btnBuscarHijos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNodo;
    private javax.swing.JTextField txtPathNodo;
    // End of variables declaration//GEN-END:variables
}
